name = "PowerWaterModels"
uuid = "7f4f7f52-2f44-4c87-b9ed-462dc784f1b2"
authors = ["Byron Tasseff", "Russell Bent", "Carleton Coffrin"]
repo = "https://github.com/lanl-ansi/PowerWaterModels.jl"
version = "0.3.0"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
WaterModels = "7c60b362-08f4-5b14-8680-cd67a3e18348"

[compat]
InfrastructureModels = "~0.7"
PowerModels = "~0.19"
PowerModelsDistribution = "~0.14"
WaterModels = "~0.9"
julia = "1.6 - 1"

[extras]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HiGHS", "Juniper", "Logging", "Ipopt"]
